#!/usr/bin/env bash
echo Creating users database...
docker-compose exec users python manage.py recreate-db
echo Creating vehicles database...
docker-compose exec vehicles python manage.py recreate-db
echo Creating ratings database...
docker-compose exec ratings python manage.py recreate-db
echo Creating stops database...
docker-compose exec stops python manage.py recreate-db
echo Filling stops database...
docker-compose exec stops python manage.py seed-db
