echo Creating users database...
run docker-compose exec users python manage.py recreate-db
echo Creating vehicles database...
run docker-compose exec vehicles python manage.py recreate-db
echo Creating ratings database...
run docker-compose exec ratings python manage.py recreate-db
echo Creating stops database...
run docker-compose exec stops python manage.py recreate-db
echo Filling stops database...
run docker-compose exec stops python manage.py seed-db
