version: '3.6'

services:

  users: # Users run
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - ./services/users:/usr/src/app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_db
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ratings: # Ratins don't run
    build:
      context: ./services/ratings
      dockerfile: Dockerfile
    volumes:
      - ./services/ratings:/usr/src/app
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@ratings-db:5434/ratings_db
    depends_on:
      - ratings-db

  ratings-db:
    build:
      context: ./services/ratings/project/db
      dockerfile: Dockerfile
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  stops: # Stops run
    build:
      context: ./services/stops
      dockerfile: Dockerfile
    volumes:
      - ./services/stops:/usr/src/app
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@stops-db:5435/stops_db
    depends_on:
      - stops-db

  stops-db:
    build:
      context: ./services/stops/project/db
      dockerfile: Dockerfile
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  vehicles: # Vehicles don't run
    build:
      context: ./services/vehicles
      dockerfile: Dockerfile
    volumes:
      - ./services/vehicles:/usr/src/app
    ports:
      - "5004:5004"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@vehicles-db:5436/vehicles_db
    depends_on:
      - vehicles-db

  vehicles-db:
    build:
      context: ./services/vehicles/project/db
      dockerfile: Dockerfile
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  interface: # interface doesn't run
    build:
      context: services/interface
      dockerfile: Dockerfile
    volumes:
      - ./services/interface:/usr/src/app
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig