version: '3.6'

services:

  users: # Users run
    build:
      context: ./services/users
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - PORT=5001
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5433/users_db
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  vehicles:
    build:
      context: ./services/vehicles
      dockerfile: Dockerfile
    ports:
      - 5004:5004
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@vehicles-db:5436/vehicles_db
      - USERS_URI=http://users:5001
    depends_on:
      - vehicles-db
      - users

  vehicles-db:
    build:
      context: ./services/vehicles/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#  ratings: # Ratins don't run
#    build:
#      context: ./services/ratings
#      dockerfile: Dockerfile
#    ports:
#      - 5002:5002
#    environment:
#      - PORT=5002
#      - FLASK_ENV=development
#      - APP_SETTINGS=project.config.DevelopmentConfig
#      - DATABASE_URL=postgres://postgres:postgres@ratings-db:5434/ratings_db
#    depends_on:
#      - ratings-db
#      - users
#      - stops
#
#  ratings-db:
#    build:
#      context: ./services/ratings/project/db
#      dockerfile: Dockerfile
#    ports:
#      - "5434:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#  stops: # Stops run
#    build:
#      context: ./services/stops
#      dockerfile: Dockerfile
#    ports:
#      - "5003:5003"
#    environment:
#      - FLASK_ENV=development
#      - APP_SETTINGS=project.config.DevelopmentConfig
#      - DATABASE_URL=postgres://postgres:postgres@stops-db:5435/stops_db
#    depends_on:
#      - stops-db
#
#  stops-db:
#    build:
#      context: ./services/stops/project/db
#      dockerfile: Dockerfile
#    ports:
#      - "5435:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres

  interface:
    build:
      context: ./services/interface
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - PORT=5005
      - USERS_URI=http://users:5001
      - VEHICLES_URI=http://vehicles:5004
    depends_on:
      - vehicles
      - users